create table participants(id bigint generated by default as identity primary key,name text unique not null,quiniela text not null,column_number int not null);
create table jornadas(id bigint generated by default as identity primary key,number int unique not null,date date,results jsonb,pleno15 text);
create table scores(id bigint generated by default as identity primary key,jornada_id bigint references jornadas(id) on delete cascade,participant_id bigint references participants(id) on delete cascade,hits int not null default 0,unique(jornada_id,participant_id));
insert into participants(name,quiniela,column_number) values
('Christian','Q1',1),('Cristina','Q1',2),('Natalia','Q1',3),('Sandra','Q1',4),('Helen','Q1',5),('Xavi','Q1',6),('Moha','Q1',7),('Noe','Q1',8),
('Loren','Q2',1),('Taly','Q2',2),('Puertas','Q2',3),('Ivan','Q2',4),('Pardo','Q2',5),('Jabi','Q2',6),('Cristina A.','Q2',7),('Eva','Q2',8);